name: M&#35; blog
description: "() => melkio.OnStage();"
url: http://melkio.codiceplastico.com
markdown: kramdown
pygments: true
auto: true
paginate: 5
paginate_path: "/page:num"
title: M&#35; blog

encoding: utf-8
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# Disqus Comments
disqus_short_name: melkio
disqus_show_comment_count: true
